# Generated by Django 2.2.1 on 2019-05-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_moreinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='moreInfo',
            new_name='more_info_url',
        ),
        migrations.AddField(
            model_name='job',
            name='usability_status',
            field=models.CharField(default='idea only', max_length=200),
            preserve_default=False,
        ),
    ]
