# Generated by Django 2.2.1 on 2019-05-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190515_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='key_technologies',
            field=models.CharField(default='Plugin Idea', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Plug-in Idea', max_length=80),
            preserve_default=False,
        ),
    ]
