# Generated by Django 2.2.1 on 2019-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190515_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(default='intermediate', max_length=30),
            preserve_default=False,
        ),
    ]
