# Generated by Django 2.2.1 on 2019-06-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_idea_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='idea_by',
            new_name='photographer',
        ),
    ]
