# Generated by Django 2.2.1 on 2019-06-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190628_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='key_technologies',
            new_name='camera_model',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='usability_status',
            new_name='technique',
        ),
    ]
