# Generated by Django 2.2.1 on 2019-06-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190628_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo_studio',
            field=models.CharField(default='individual', max_length=70),
        ),
    ]
