# Generated by Django 2.2.1 on 2019-08-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_photo_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('projections', models.CharField(blank=True, max_length=80)),
                ('license', models.CharField(blank=True, max_length=40)),
                ('price', models.CharField(blank=True, max_length=40)),
                ('info_url', models.CharField(blank=True, max_length=160)),
                ('demo_url', models.CharField(blank=True, max_length=160)),
            ],
        ),
    ]
