# Generated by Django 2.2.1 on 2019-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='distribution_method',
            field=models.CharField(blank=True, choices=[('download', 'Downloadable Library'), ('cloud', 'Cloud Service')], max_length=50),
        ),
        migrations.AddField(
            model_name='viewer',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
