# Generated by Django 2.2.1 on 2019-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20191119_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='camera_model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='technique',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
