# Generated by Django 2.2.1 on 2019-11-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191119_1814'),
        ('jobs', '0014_auto_20191119_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='detail_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
