# Generated by Django 2.0.2 on 2019-05-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
