# Generated by Django 2.2.1 on 2019-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190514_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='body3',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='body4',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='body5',
            field=models.TextField(default=' '),
        ),
    ]
