# Generated by Django 2.2.1 on 2019-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190517_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='production',
            field=models.BooleanField(default=True),
        ),
    ]
