# Generated by Django 2.2.1 on 2019-07-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='testing_tag',
            field=models.CharField(default='production', max_length=80),
        ),
    ]
