# Generated by Django 2.2.1 on 2019-11-19 18:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_testing_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='body5',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
